### PR TITLE
[OPENJPA-2748] commons-collection is updated to most recent version

### PR DESCRIPTION
**Pull request by solomax**
Additionally I would like to remove
`ReferenceMap.HARD, SOFT, WEAK` in favor of `ReferenceStrength.HARD, SOFT, WEAK`

shall I add another commit to this PR, or create another one?

this fix depends on commons-collections4 4.3-SNAPSHOT, will compile as soon as 4.3 will be released or SNAPSHOT will be uploaded

### CODE REVIEW

**Comment by ilgrosso** [comment]
Thx @solomax - this PR looks good to me.

> I would like to remove ReferenceMap.HARD, SOFT, WEAK in favor of ReferenceStrength.HARD, SOFT, WEAK
> shall I add another commit to this PR, or create another one?

To me, you can add that here.

@struberg / @rmannibucau would you please doublecheck?

**Comment by solomax** [comment]
@rmannibucau I have this setting on by default in my IDE due to I had extremely bad experience of project migration without @Override being set.
Shall I remove all these annotations?

**Comment by rmannibucau** [comment]
@solomax if possible it would be awesome to have this PR about commons-collection upgrade only and then if you want add override everywhere

**Comment by solomax** [comment]
sure, will do
will take some time :)

**Comment by solomax** [comment]
Hopefully this diff will be easier to read :)

**Comment by ilgrosso** [comment]
Ok, I am going to merge this PR right now - but please don't forget to submit another for `@override`s ;-)

**Comment by solomax** [comment]
@ilgrosso this will break the build ... most probably
4.3-SNAPSHOT might not be online ...

**Comment by ilgrosso** [comment]
@solomax let me check..

**Comment by ilgrosso** [comment]
@solomax ah I see: do you know why `4.3-SNAPSHOT` is not [there](https://repository.apache.org/content/groups/snapshots/org/apache/commons/commons-collections4/) yet?

**Comment by solomax** [comment]
I'm afraid there no auto build :(
I've asked the devs: https://markmail.org/thread/tshcd4d54nxrvgbu

Will send additional email regarding SNAPSHOT

**Comment by ilgrosso** [comment]
@solomax could you please rebase?
Anyway, I cannot see yet commons-collections4's 4.3-SNAPSHOT artifacts out there.. :-(

**Comment by solomax** [comment]
@ilgrosso could you please guide me with rebase?
I never used it :(

**Comment by ilgrosso** [comment]
> could you please guide me with rebase?
> I never used it :(

I mean something like as https://robots.thoughtbot.com/keeping-a-github-fork-updated

**Comment by solomax** [comment]
Just have tried to rebase but no luck :(
rebase against `solomax/trunk` has no effect
rebase against `apache/trunk` conflicts and I have no idea how to resolve it :(

**Comment by ilgrosso** [comment]
> rebase against apache/trunk conflicts and I have no idea how to resolve it :(

yep, you should rebasing against `apache/trunk` and solving the conflicts :-)
There have been no changes in `trunk` but yours, so I think you should be able to cope with those...

**Comment by solomax** [comment]
OK, the trick was to use `git rebase --skip` :)
But for some reason there are still 3 commits :(

**Comment by ilgrosso** [comment]
> But for some reason there are still 3 commits :(

This could be fixed too, but it is not really a big issue since we are with SVN.

**Comment by solomax** [comment]
Great :)

**Comment by ilgrosso** [comment]
ah, it seems you can merge this PR by yourself, when the commons-collection4 artifacts will be available ;-)
congrats!

**Comment by solomax** [comment]
Merged with 4709f38ba23244ad1c876ccf16704ccfdb099b73

**Pull request closed without merging**
