### PR TITLE
OPENJPA-2816 Add HerdDB DBDictionary

### PR DESCRIPTION
**Pull request by eolivelli**
- implement HerdDBDictionary
- add autodiscovery of HerdDB

### CODE REVIEW

**Comment by ilgrosso** [comment]
...no tests at all?

**Comment by rmannibucau** [comment]
@ilgrosso IT are coming but are IT (for ext db they are only meaningful if covering 100% of db version otherwise it is like having no test for all other versions ;)). We also have issues with our IT as mentionned by Mark on the list and it hits here so need a few days.

**Comment by ilgrosso** [comment]
We do have treats for other in-memory dbms, I was thinking to include the news one.
...and "some test" is always better than "no tests".

**Comment by rmannibucau** [comment]
@ilgrosso agree, point was more that IMHO it is more important to make it its way on master than to get an IT which is not straight forward yet (a mix between both the DB and our own lacks of our suite). To be concrete I expect a snapshot to be grabbable in the coming days for CI to catch/test up with the newt config so test are pushed to another PR. Hope it makes sense.

**Pull request merged**
