### PR TITLE
[OPENJPA-2902] fix H2 Dictionary autoAssignClause value

### PR DESCRIPTION
**Pull request by fuubo**
according to https://github.com/h2database/h2database/issues/3386, `identity` is invalid.

### CODE REVIEW

**Review by rmannibucau — APPROVED** [review]

**Comment by solomax** [comment]
@fuubo can you please create JIRA here: https://issues.apache.org/jira/projects/OPENJPA ?
so we can merge this one and get the line in CHANGELOG :)))

**Comment by fuubo** [comment]
> @fuubo can you please create JIRA here: https://issues.apache.org/jira/projects/OPENJPA ? so we can merge this one and get the line in CHANGELOG :)))

https://issues.apache.org/jira/browse/OPENJPA-2902

**Comment by solomax** [comment]
Hello @fuubo,

just tried to run current tests without your fix

My steps were:

1. modified https://github.com/apache/openjpa/blob/master/pom.xml#L470
```
diff --git a/pom.xml b/pom.xml
index 1b2516694..c512df03b 100644
--- a/pom.xml
+++ b/pom.xml
@@ -474,9 +474,9 @@
                 </property>
             </activation>
             <properties>
-                <h2.version>2.0.202</h2.version>
+                <h2.version>2.1.210</h2.version>
                 <connection.driver.name>org.h2.Driver</connection.driver.name>
-                <connection.url>jdbc:h2:./target/database/openjpa-h2-database</connection.url>
+                <connection.url>jdbc:h2:./target/database/openjpa-h2-database;MODE=STRICT</connection.url>
                 <connection.username />
                 <connection.password />
                 <!-- TCK specific properties -->
```
2. Run `mvn clean install -Ptest-h2-2` 

Got lots of errors in `SELECT ` statements

I guess I should get some errors in CREATE DATABASE statements without your fix
What am I doing wrong?

**Comment by solomax** [comment]
@fuubo ping? :)))

**Pull request closed without merging**
