### PR TITLE
OPENJPA-2819 Add simple GitHub Actions validation for Pull Requests

### PR DESCRIPTION
**Pull request by eolivelli**
Add simple pull request validation.
Starting from the github actions template https://github.com/actions/starter-workflows/blob/master/ci/maven.yml

### CODE REVIEW

**Comment by rmannibucau** [comment]
Looks good to me now, only thing to decide is if we keep on push or not (does not hurt I think and can be good for us).
Waiting for a passing build then I think we can merge.


cc @ilgrosso @struberg want to have a look?

**Comment by ilgrosso** [comment]
@eolivelli why "only" `package`? Why not `install`?

@rmannibucau +1 to add it to push as well.

**Comment by eolivelli** [comment]
@ilgrosso thanks for your review

There is not need to 'install'.
With 'install' Maven copies the jar to .m2.

It looks like the build works without it.
Probably 'verify' could work ad well

**Comment by ilgrosso** [comment]
Agree then, go on with verify

**Comment by eolivelli** [comment]
@ilgrosso done

**Comment by eolivelli** [comment]
If you commit this change github actions will automatically be activated probably

**Comment by eolivelli** [comment]
The build fails with verify

[ERROR] /home/runner/work/openjpa/openjpa/openjpa-examples/openbooks/build.xml:117: *** Error:
[ERROR] 		   The directory for OpenJPA libraries can not be located at /home/runner/.m2/repository/org/apache/openjpa/openjpa-all/3.1.3-SNAPSHOT.
[ERROR] 		   Make sure openjpa.lib property value is correct in build.properties file.
[ERROR] around Ant part ...<ant

**Comment by eolivelli** [comment]
this is a demo run:
https://github.com/eolivelli/openjpa/runs/883352848

**Comment by eolivelli** [comment]
It looks like the ant plugin looks for openjpa lib into local Maven repository.
I will change the goal to 'install' as @ilgrosso suggested

**Comment by eolivelli** [comment]
try again:
https://github.com/eolivelli/openjpa/runs/883449807

**Comment by eolivelli** [comment]
@ilgrosso @rmannibucau @struberg an you please commit this patch ?
it looks like it works very well
https://github.com/eolivelli/openjpa/runs/883449807

**Comment by rmannibucau** [comment]
+1 from me

**Pull request merged**
